-- ============================================================
-- 0078_payment_request_webhook.sql
-- ⚠️ ALREADY DONE VIA THE DASHBOARD (2026-08-03) — DO NOT RUN.
--
-- The payment-request webhook was created in the UI as a "Supabase Edge
-- Functions" webhook on `payment_request_lines` INSERT → dynamic-action.
-- Running this file as well would put a SECOND trigger on the same table and
-- every request would notify residents TWICE.
--
-- Kept only as the reference for how to recreate it in SQL (e.g. rebuilding the
-- project from scratch), the same way 0017 documents the dues webhooks. Check
-- before running:
--
--   SELECT tgname FROM pg_trigger
--    WHERE tgrelid = 'public.payment_request_lines'::regclass AND NOT tgisinternal;
--
--   trg_notify_payment_request     = the in-app bell (0077)
--   anything else                  = the webhook already exists, STOP
--
-- Where the page moved: Database → Webhooks is now Integrations → Database
-- Webhooks. Choosing type "Supabase Edge Functions" fills the URL and auth in
-- for you, which is why the UI route is the easy one.
--
-- NOTE ON AUTH: dynamic-action does NOT check an Authorization header. Its only
-- gate is the optional `x-webhook-secret` (index.ts), which is inert until
-- WEBHOOK_SECRET is set — see DEPENDENCIES.md, still unset. The existing
-- charges/payments/dues webhooks carry no auth header either. An earlier draft
-- of this file told you to add a Bearer token; that was wrong.
-- ============================================================

-- DROP TRIGGER IF EXISTS notify_payment_request_insert ON public.payment_request_lines;
-- CREATE TRIGGER notify_payment_request_insert
-- AFTER INSERT ON public.payment_request_lines
-- FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request(
--   'https://miyrsnlpftybmudiuhbi.supabase.co/functions/v1/dynamic-action',
--   'POST',
--   '{"Content-Type":"application/json"}',
--   '{}',
--   '5000'
-- );
